/*
 * @Author: sumail sumail@xyzzdev.com
 * @Date: 2024-07-02 16:10:47
 * @LastEditors: sumail sumail@xyzzdev.com
 * @LastEditTime: 2025-11-11 20:06:06
 * @FilePath: /nextjs/travel-dairy/src/app/layout.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%
 */
'use client';

import type { Metadata } from 'next';
import { useSelectedLayoutSegment } from 'next/navigation';
import { Inter, Source_Sans_3, Roboto, Aleo } from 'next/font/google';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { store, persistor } from '@/store';
import { increment } from '@/store/reducers/counter.slice';
import { useAppDispatch } from '@/store/hooks';
import { NextUIProvider } from '@nextui-org/react';
import { motion, AnimatePresence } from 'motion/react';
import { usePathname } from 'next/navigation';
import './globals.css';
import { useEffect, useState } from 'react';
import { initTracker } from '@/app/utils/tracker';
import usePageStay from '@/hooks/usePageStay';

const inter = Inter({ subsets: ['latin'] });
const aleo = Aleo({ subsets: ['vietnamese'] });
const SOURCE = Source_Sans_3({ weight: '400', subsets: ['cyrillic'] });

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: '/favicon-16x16.png'
//   }
// };


export default function RootLayout({
  children,
  sidemenu,
  navbar,
}: Readonly<{
  children: React.ReactNode;
  sidemenu: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  const segment = useSelectedLayoutSegment();
  const navSegment = useSelectedLayoutSegment('sidemenu');
  const pathname = usePathname();
  usePageStay();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  useEffect(() => {
    initTracker({ reportUrl: '/api/track', userId: '888' });

    console.log('layout');
  }, []);

  return (
    <html lang='en'>
      <body className={aleo.className}>
        {/* {mounted ? ( */}
        <NextUIProvider>
          <Provider store={store}>
            <PersistGate persistor={persistor} loading={<div>ddd</div>}>
              <AnimatePresence initial={false}>
                <motion.div
                  key={pathname}
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ ease: 'easeInOut', duration: 0.75 }}
                >
                  {navbar}
                  {children}
                  {sidemenu}
                </motion.div>
              </AnimatePresence>
            </PersistGate>
          </Provider>
        </NextUIProvider>

        {/* ) : <div>ddd</div>} */}
      </body>
    </html>
  );
}
